### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by A1X5H04** [Daydreamer-riri/transition-hooks#1]
I am getting the following error while using the components, almost any components 

![image](https://github.com/user-attachments/assets/7330ec1b-863f-413b-ba60-65a0bc848621)

**Comment by Daydreamer-riri** [comment]
This was related to my build process. Thank you so much for reporting this issue! I will release a new version today to fix this issue.

**Comment by Daydreamer-riri** [comment]
This issue should have been resolved in v0.3.1. You can try it and let me know if there are any problems.

**Comment by A1X5H04** [comment]
Thank you for this wonderful library
