### ISSUE TITLE
When using useListTransition, updating an array of objects often leads to a duplicate div in the DOM

### ISSUE THREAD

**Issue by kyle-ahlstrom** [Daydreamer-riri/transition-hooks#2]
When using an array of Objects along with the useListTransition hook, I am getting an animation bug where a duplicate div is added into the DOM momentarily and then removed when one of the Objects in the Array is updated resulting in an animation bug. I have ensured that we are using the KeyExtractor correctly and that each parent div has a unique key but I still see this bug persist. 

Example:
![bug example](https://github.com/user-attachments/assets/9b183bd6-505b-4e2d-9aa1-6bb4b3262e3d)

Code Sandbox (not always reproducible but you can see it occasionally happen when clicking the 'update last item' button) :
https://codesandbox.io/p/sandbox/transition-test-forked-7v4hcm

**Comment by Daydreamer-riri** [comment]
‌‌Hi @kyle-ahlstrom, thank you for identifying this issue! The problem has now been resolved, and you can use v0.3.2 to confirm whether this issue will reoccur.

**Comment by kyle-ahlstrom** [comment]
@Daydreamer-riri it looks like it's resolved now! thank you for the quick response!
