### ISSUE TITLE
[Question] Will there be more transitions hooks 

### ISSUE THREAD

**Issue by A1X5H04** [Daydreamer-riri/transition-hooks#3]
I really like your transition library, I just want to know that will you support more of the transtions hooks like:

- `useMorph` : To morph from one state to another
- `useCascade` : To cascade animations in the list when showing 
etc..

**Comment by Daydreamer-riri** [comment]
Can you describe them in more detail? The original purpose of this library is to implement a modern react-transition-group, so there is currently no further plan. But suggestions welcome!

**Comment by A1X5H04** [comment]
https://brunnolou.github.io/react-morph/

Something like this

**Comment by Daydreamer-riri** [comment]
> https://brunnolou.github.io/react-morph/
> 
> Something like this

Now the browser's built-in view-transitiion API can achieve this effect well. An easy-to-use hook can be implemented via the wrapper of view-transition (like useListTransiton).

But I don't have time to implement it at the moment😂, PR welcome.
